version: '3.0'
services:
  thream-api:
    container_name: ${COMPOSE_PROJECT_NAME}
    build:
      context: './'
    env_file:
      - '.env'
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - 'thream-database'
    volumes:
      - './uploads:/usr/src/app/uploads'
    restart: 'unless-stopped'

  thream-database:
    container_name: 'thream-database'
    image: 'postgres:14.2'
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'thream'
    volumes:
      - 'database-volume:/var/lib/postgresql/data'
    restart: 'unless-stopped'

volumes:
  database-volume:
