version: '3.0'
services:
  thream-api:
    container_name: ${COMPOSE_PROJECT_NAME}
    build:
      context: './'
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - ${DATABASE_HOST}
      - 'thream-maildev'
    volumes:
      - './:/api'
    restart: 'unless-stopped'

  thream-phpmyadmin:
    container_name: 'thream-phpmyadmin'
    image: 'phpmyadmin/phpmyadmin:5.0.4'
    environment:
      PMA_HOST: ${DATABASE_HOST}
      PMA_PORT: ${DATABASE_PORT}
      PMA_USER: ${DATABASE_USER}
      PMA_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '8000:80'
    depends_on:
      - ${DATABASE_HOST}
    restart: 'unless-stopped'

  thream-database:
    container_name: ${DATABASE_HOST}
    image: 'mysql:8.0.23'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_TCP_PORT: ${DATABASE_PORT}
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    volumes:
      - 'database-volume:/var/lib/mysql'
    restart: 'unless-stopped'

  thream-maildev:
    container_name: 'thream-maildev'
    image: 'maildev/maildev:1.1.0'
    ports:
      - '1080:80'
    restart: 'unless-stopped'

volumes:
  database-volume:
