services:
  workspace:
    build:
      context: "./"
      dockerfile: "./Dockerfile"
    volumes:
      - "..:/workspace:cached"
    command: "sleep infinity"
    network_mode: "host"

  thream-database:
    image: "postgres:15.4"
    environment:
      POSTGRES_USER: "thream_user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "thream"
    volumes:
      - "thream-postgres-data:/var/lib/postgresql/data"
    restart: "unless-stopped"
    network_mode: "host"

volumes:
  thream-postgres-data:
