version: '3.0'

services:
  workspace:
    build:
      context: './'
      dockerfile: './Dockerfile'
    volumes:
      - '..:/workspace:cached'
    command: 'sleep infinity'

  thream-database:
    image: 'postgres:14.0'
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'thream'
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    restart: 'unless-stopped'

  thream-maildev:
    image: 'maildev/maildev:1.1.0'
    ports:
      - '1080:80'

volumes:
  postgres-data:
