name: 'Release'

on:
  push:
    branches: [master]

jobs:
  release:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3.5.0'
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: 'Import GPG key'
        uses: 'crazy-max/ghaction-import-gpg@v3.2.0'
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          git-user-signingkey: true
          git-commit-gpgsign: true

      - name: 'Use Node.js'
        uses: 'actions/setup-node@v3.6.0'
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: 'Install'
        run: 'npm install'

      - name: 'Build'
        run: 'npm run build'

      - run: 'npm run build:typescript'

      - name: 'Release'
        run: 'npm run release'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_COMMITTER_NAME: ${{ secrets.GIT_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_EMAIL }}
