name: 'Test'

on:
  push:
    branches: [develop]
  pull_request:
    branches: [master, develop]

jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3.5.3'

      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v3.6.0'
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: 'Install dependencies'
        run: 'npm clean-install'

      - name: 'Build'
        run: 'npm run build'

      - run: 'cp .env.example .env'

      - name: 'Test'
        run: 'npm run test'
