name: 'Test'

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'

      - name: 'Use Node.js'
        uses: 'actions/setup-node@v2.1.5'
        with:
          node-version: '16.x'

      - name: 'Install'
        run: 'npm ci --cache .npm --prefer-offline'

      - name: 'Test'
        run: 'npm run test'
